service: desafio-bgc

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
      Resource: arn:aws:dynamodb:${self:provider.region}:*:table/ProdutosMaisVendidosPorCategoria

functions:
  find:
    handler: src/handlers/handler.find
    events:
      - http:
          path: find
          method: get
