service: desafio-bgc

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:Scan
      Resource: arn:aws:dynamodb:${self:provider.region}:*:table/ProdutosMaisVendidosPorCategoria
    
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource:
        - arn:aws:lambda:${self:provider.region}:*:function:${self:service}-${self:provider.stage}-find
        - arn:aws:lambda:${self:provider.region}:*:function:${self:service}-${self:provider.stage}-set

functions:
  find:
    handler: src/handlers/get.find
    events:
      - http:
          path: find
          method: get
          
  set:
    handler: src/handlers/post.set
    events:
      - http:
          path: set
          method: post
