service: my-lambda-project

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-east-1

functions:
  welcome:
    handler: src/handlers/handler.welcome
    events:
      - http:
          path: welcome
          method: get

